<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="preyas-r" name="Runners.MyAccount_Runner" tests="1" failures="1" timestamp="2022-05-24T17:27:53 IST" time="34.924" errors="0">
  <testcase name="runScenario" time="34.924" classname="Runners.MyAccount_Runner">
    <failure type="java.lang.AssertionError" message="expected [Account details changed successfully.] but found [Account details changed successfully.1]">
      <![CDATA[java.lang.AssertionError: expected [Account details changed successfully.] but found [Account details changed successfully.1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at StepDefinition.MyAccountsteps.click_on_savechanges_button(MyAccountsteps.java:144)
at âœ½.click on savechanges button(file:///home/preyas.r@ah.zymrinc.com/Desktop/preyas/eclipse-workspace/git_project/src/test/resources/Features/myaccount/001.myaccount.accdetails.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runners.MyAccount_Runner -->
